name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.5'
    - name: Build
      run: stack build
    - name: Test
      run: make coverage
    - name: Benchmark
      run: stack bench
